version: 2
jobs:
  install:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/tmp
    docker:
     - image: tesutoproject/ui:0.2
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run test
  lint:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run lint
  e2e:
    working_directory: ~/tmp
    docker:
      - image: rogargon/angular-e2e
    steps:
    - attach_workspace:
        at: ~/tmp
    - run: npm run e2e
workflows:
  version: 2
  ui:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
