version: 2
jobs:
  install:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/tmp
    docker:
     - image: tesutoproject/ui:0.2
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run test
  lint:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run lint
  build:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: npm run build -- --aot

workflows:
  version: 2
  ui:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
                - develop
