version: 2
jobs:
  install:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - checkout
      - run: npm install
  test:
    working_directory: ~/tmp
    docker:
     - image: tesutoproject/ui:0.2
    steps:
    - run: npm run test
  lint:
    working_directory: ~/tmp
    docker:
      - image: tesutoproject/ui:0.2
    steps:
      - run: npm run lint
workflows:
  version: 2
  ui:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
